language: android

env:
  global:
    - secure: gedzEaFgsSlsllrGWGk7xFhau9gGna96J9Jp30HhUVcnWA9G8m7J7lOeTdV2i7ZkDTTQY/s2yB3wSVu4Bm4L8twJQDcARIEchlZ0s2In3DSjV0psce8WOLe1KKbh76viKz6W/LNyFgDLiGXDdns5Nv09/Eu8vN0nh4kRQfSdaVw=

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19

notifications:
  email:
    recipients:
      - $HARRISON_BOXCAR_EMAIL
    on_success: always
    on_failure: always

script: ant debug

#deploy:
#  provider: releases
#  api-key: "GITHUB OAUTH TOKEN"
#  file: "bin/Lighthouse.apk"
#  skip_cleanup: true
#  on:
#    tags: true
#    all_branches: true
